---
name: module3_task4

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    branches:    
      - main

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run file sh
        run: cd module3_task4 && ./setup.sh

      - name: Run make build
        run: cd module3_task4 && make build

      - name: Test
        run: |
          cd module3_task4
          make integration-tests
          make unit-tests
          make package
          make clean

      - name: Release
        env:
          TOKEN: ${{ secrets.TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 1.0.0
          files: |
            module3_task4/awesome-website.zip
            module3_task4/DEPLOY.md

      - name: Archive a ZIP file
        uses: actions/upload-artifact@v3
        with:
          name: awesome website
          path: module3_task3/awesome-website.zip
