---
name: module3_task2
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout  # Download code from the repository
        uses: actions/checkout@v3
      - name: Run file sh
        run: cd module3_task2 && ./setup.sh
      - name: Run make build  # Execute the command make build
        run: cd module3_task2 && make build
      - name: Test
        run: |
          cd module3_task2
          make test
          make unit-tests
          make integration-tests
          make package
          make clean
      - name: Archive a ZIP file
        uses: actions/upload-artifact@v3
        with:
          name: Awesome-website.zip
          path: module3_task2/awesome-website.zip
